### ISSUE TITLE
全家的地址 數字是全形

### ISSUE THREAD

**Issue by kayac-chang** [kayac-chang/the-overlord-of-beggars#17]
### 預期行為

全家的地址 數字要是半形

### 實際行為

全家的地址 數字是全形

## 參考解
https://stackoverflow.com/questions/2422177/python-how-can-i-replace-full-width-characters-with-half-width-characters

**Comment by virgil724** [comment]
https://docs.pydantic.dev/2.9/api/functional_validators/#pydantic.functional_validators.BeforeValidator

可以從這邊下手處理嗎


```python
import unicodedata
from pydantic import BeforeValidator,BaseModel
from typing_extensions import Annotated

def fWidth2hWidth(source:str):
    return unicodedata.normalize('NFKC', source)

CustomAddress=Annotated[str,BeforeValidator(fWidth2hWidth)]


class  TestModel(BaseModel):
    address :CustomAddress
```
結果大概像這樣
