### ISSUE TITLE
Table row cursor style

### ISSUE THREAD

**Issue by AlliesChen** [kayac-chang/the-overlord-of-beggars#2]
As the table row is expandable, would it be better with css style: `cursor: pointer`?

**Comment by kayac-chang** [comment]
新的版本改成：點擊 **展開按鈕** 才會展開 **即期品表單** 。

<img width="1141" alt="Screenshot 2024-10-21 at 1 34 04 PM" src="https://github.com/user-attachments/assets/0caf04f5-9898-4f0f-a151-98f14a5a4aa3">
