### ISSUE TITLE
搜尋結果查無店家時，需讓用戶知道查無任何店家

### ISSUE THREAD

**Issue by kayac-chang** [kayac-chang/the-overlord-of-beggars#7]
### Expected Behavior

當用戶的搜尋結果回傳沒有任何店家時，畫面需告知用戶查無任何店家。

### Actual Behavior

當用戶的搜尋結果回傳沒有任何店家時，店家表單呈現為空。
用戶反饋以為程式沒反應。

賞金：50塊

**Comment by JohnsonMao** [comment]
承接這項懸賞
